### ISSUE TITLE
Destructor

### ISSUE THREAD

**Issue by chris-steele** [cgkineo/adapt-youtube#1]
Need to do some clean up when component is destroyed; probably just remove player event listener(s).

**Comment by moloko** [comment]
I don't think it's going to be possible to remove the player event listeners. Not only does the API state that `removeEventListener` needs to supply the second argument as a String rather than a function reference (?!?!) - which isn't going to work for us - even then it doesn't seem to be working, see issues [6951](https://code.google.com/p/gdata-issues/issues/detail?&id=6951) and [6700](https://code.google.com/p/gdata-issues/issues/detail?&id=6700) - the latter issue has been open for over a year now so I don't expect this to be fixed in a hurry!

I'm just going to add a `remove` function that calls `player.destroy()`, that should be good enough

**Comment by moloko** [comment]
done in [v1.0.1](releases/tag/v1.0.1)
